baseURL = "https://clouscard-alerte.netlify.app/"
languageCode = "fr-FR"
title = "Clouscard Alerte"
theme = "PaperMod"
defaultContentLanguage = "fr"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  author = "Clouscard Alerte"
  description = "Site de référence sur Michel Clouscard"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowShareButtons = false
  defaultTheme = "auto"
  ShowTaxonomies = true

[params.homeInfoParams]
  Title = "Clouscard Alerte"
  Content = "Site de référence sur la pensée de Michel Clouscard"

[[params.socialIcons]]
  name = "email"
  url = "mailto:contact@clouscard-alerte.org"

[menu]
  [[menu.main]]
    name = "Articles"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Catégories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "À propos"
    url = "/about/"
    weight = 3